# Generated by Django 2.2.26 on 2022-09-11 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 9, 11, 9, 0, 43, 898610, tzinfo=utc), verbose_name='date created')),
                ('started_date', models.DateTimeField(blank=True, null=True, verbose_name='date started')),
                ('finished_date', models.DateTimeField(blank=True, null=True, verbose_name='date finished')),
                ('played', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('download_only', models.BooleanField(default=False)),
                ('gamesystems', models.ManyToManyField(to='gaming.Gamesystem')),
            ],
        ),
    ]
