# Generated by Django 4.1 on 2022-09-11 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gamesystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "created_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            9,
                            11,
                            13,
                            32,
                            26,
                            837952,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="date created",
                    ),
                ),
                (
                    "started_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date started"
                    ),
                ),
                (
                    "finished_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date finished"
                    ),
                ),
                ("played", models.BooleanField(default=False)),
                ("finished", models.BooleanField(default=False)),
                ("download", models.BooleanField(default=False)),
                ("gamesystems", models.ManyToManyField(to="gaming.gamesystem")),
            ],
        ),
    ]
