# Generated by Django 2.2.26 on 2022-08-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesystem',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='gamesystems',
            field=models.ManyToManyField(to='gaming.Gamesystem'),
        ),
    ]
