# Generated by Django 4.1.2 on 2022-10-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
    ]
