# Generated by Django 4.1.2 on 2023-02-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_alter_game_created_date'),
        ('gaming', '0002_auto_20220914_1528'),
    ]

    operations = [
    ]
