# Generated by Django 4.1.2 on 2023-02-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0003_merge_20230207_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='download',
            new_name='download_only',
        ),
    ]
